[build]
  publish = "."
  functions = "functions"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . /"

# Redirect API calls to the corresponding function
[[redirects]]
  from = "/api/conference/register"
  to = "/.netlify/functions/conference-register"
  status = 200
  force = true

[[redirects]]
  from = "/api/conference/visibility"
  to = "/.netlify/functions/conference-visibility"
  status = 200
  force = true

[[redirects]]
  from = "/api/conference/:conferenceId/attendees"
  to = "/.netlify/functions/conference-attendees?conferenceId=:conferenceId"
  status = 200
  query = { currentUserId = ":currentUserId" }
  force = true

[[redirects]]
  from = "/api/conference/history"
  to = "/.netlify/functions/conference-history"
  status = 200
  force = true

[[redirects]]
  from = "/api/conference/save-qr"
  to = "/.netlify/functions/conference-save-qr"
  status = 200
  force = true

[[redirects]]
  from = "/api/debug/*"
  to = "/.netlify/functions/debug-store"
  status = 200
  force = true

# Functions configuration
[functions]
  directory = "functions"
  external_node_modules = ["@supabase/supabase-js", "faunadb"]
